[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gupax_mobile"
version = "1.1.0"
authors = [
  { name="Gupax Community" },
]
description = "Standalone Monero & P2Pool mining manager with standard Graphical UI (Tkinter) and TUI for Desktop and Mobile"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Environment :: X11 Applications",
    "Environment :: Console",
]

[project.scripts]
gupax = "gupax_mobile.main:main"
gupax-mobile = "gupax_mobile.main:main"
gupax-gui = "gupax_mobile.main:main"
